name: build

on:
  workflow_dispatch:
  push:
    branches: [main, dev, "dev/*", "feature/*", "rel/*"]
    paths-ignore:
      - readme.md
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  CI_BUILD: true

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: install web compiler
        run: dotnet tool install Excubo.WebCompiler --global

      - name: build web artifacts
        working-directory: ./src
        run: webcompiler ./web/mark.davison.file.web.ui/compilerconfig.json

      - name: build
        working-directory: ./src
        run: dotnet build ./mark.davison.file.sln

      - name: test
        working-directory: ./src
        run: dotnet test ./mark.davison.file.sln --filter "TestCategory!=UI"

  build-image-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/api.dockerfile
          context: ./src
          push: false

  build-image-bff-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/bff-web.dockerfile
          context: ./src
          push: false

  build-image-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/web.dockerfile
          context: ./src
          push: false
